version: '3.9'
  
services:
  redis:
    image: "redis:alpine"
    build: ./redis
  web:
    build: ./web
    ports:
      - 443:443
    secrets:
      - ssl_certfile
      - ssl_keyfile

secrets:
  ssl_certfile:
    file: ./secrets/ssl_certs/test.crt
  ssl_keyfile:
    file: ./secrets/ssl_certs/test.key