# Use the official redis image as the base image
FROM redis:alpine

# copy custom configuration file
# COPY redis.conf /usr/local/etc/redis/redis.conf

# set environment variables
# ENV REDIS_PORT 6379

# Expose the redis port
EXPOSE 6379

# Specify a command to run redis
# CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
